vich_uploader:
    db_driver: orm

    mappings:
       news_images:
           uri_prefix: '%app.path.news_images%'
           upload_destination: '%kernel.project_dir%/public/uploads'
       org_news_attachments:
           uri_prefix: '%app.path.news_images%'
           upload_destination: '%kernel.project_dir%/public/uploads/attachments'
