# \config\packages\news.yaml

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    app_controller:
        namespace: Sibintek\NewsBundle\Controller\
        resource: '@NewsBundle/src/Controller'
        tags: ['controller.service_arguments']

#    Sibintek\InformerBundle\Controller\StaticDataController: ~
#    Sibintek\InformerBundle\Controller\WeatherController: ~
    Sibintek\NewsBundle\Repository\OrgNewsRepository: ~


